Fixing a crash due to None type passed to map
Diaphora will crash if GetManyBytes returns a None type (such as on externs in arm64) after its being passed to the map function:

Error: argument 2 to map() must support iteration
Traceback (most recent call last):
  File "./diaphora.py", line 3690, in _diff_or_export
    bd.export()
  File "./diaphora.py", line 1502, in export
    self.do_export()
  File "./diaphora.py", line 1478, in do_export
    props = self.read_function(func)
  File "./diaphora.py", line 1127, in read_function
    bytes_sum += sum(map(ord, curr_bytes))
TypeError: argument 2 to map() must support iteration

This patch seems to fix the hard crash... it will just continue and seems to have no adverse affects.